# Generated by Django 4.1.1 on 2022-10-10 14:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Management",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("type", models.CharField(max_length=22)),
                ("date", models.CharField(max_length=10)),
                ("value", models.IntegerField()),
                ("cpf", models.CharField(max_length=12)),
                ("card", models.CharField(max_length=20)),
                ("hour", models.CharField(max_length=8)),
                ("store_property", models.CharField(max_length=30)),
                ("store_name", models.CharField(max_length=30)),
                (
                    "store_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Management",
                        to="store.store",
                    ),
                ),
            ],
        ),
    ]
