# Generated by Django 4.1.1 on 2022-10-09 14:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Management",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("type", models.IntegerField()),
                ("date", models.IntegerField()),
                ("value", models.IntegerField()),
                ("cpf", models.IntegerField()),
                ("card", models.CharField(max_length=20)),
                ("hour", models.IntegerField()),
                ("store_property", models.CharField(max_length=30)),
                ("store_name", models.CharField(max_length=30)),
            ],
        ),
    ]
