# Generated by Django 4.1.1 on 2022-10-09 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_alter_store_options_alter_store_managers_and_more"),
        ("management", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="management",
            name="store_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Management",
                to="store.store",
            ),
        ),
    ]
