# Generated by Django 4.1.1 on 2022-10-09 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0003_alter_management_store_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="management",
            name="type",
            field=models.CharField(max_length=22),
        ),
    ]
