# Generated by Django 4.1.1 on 2022-10-09 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="store",
            options={},
        ),
        migrations.AlterModelManagers(
            name="store",
            managers=[],
        ),
        migrations.RemoveField(
            model_name="store",
            name="date_joined",
        ),
        migrations.RemoveField(
            model_name="store",
            name="email",
        ),
        migrations.RemoveField(
            model_name="store",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="store",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="store",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="store",
            name="is_staff",
        ),
        migrations.RemoveField(
            model_name="store",
            name="is_superuser",
        ),
        migrations.RemoveField(
            model_name="store",
            name="last_login",
        ),
        migrations.RemoveField(
            model_name="store",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="store",
            name="password",
        ),
        migrations.RemoveField(
            model_name="store",
            name="user_permissions",
        ),
        migrations.RemoveField(
            model_name="store",
            name="username",
        ),
    ]
